### ISSUE TITLE
Consider normalizing :focus instead of removing it

### ISSUE THREAD

**Issue by lsorber** [jaydenseric/Fix#1]
Please consider normalizing `:focus` instead of removing its styling completely. As you mention in your blog post, `:focus` serves an important role in the accessibility of a web page.

The problem is, what should we normalize the style to? Below is a screenshot of a zoomed-in anchor on the latest version of Chrome on OS X to inspect the default style.
![screen shot 2016-01-15 at 10 54 53](https://cloud.githubusercontent.com/assets/4543654/12350588/4a160f3e-bb78-11e5-91c6-2c82258c0e4c.png)

If we take this style as the norm, it can be almost completely reproduced with

``` css
:focus:not(:hover):not(:active) {
    outline: 0;
    border-radius: 1px;
    box-shadow: inset 0 0 0 1px rgba(57, 153, 255, 0.25),
        0 0 0 2px rgba(57, 153, 255, 0.40),
        0 0 0 3px rgba(57, 153, 255, 0.25);
}
```

The result is fairly close to the default style:
![screen shot 2016-01-15 at 11 44 05](https://cloud.githubusercontent.com/assets/4543654/12351373/4f708180-bb7d-11e5-9b20-2e0e53f839c8.png)
At 100% it renders like this:
![screen shot 2016-01-15 at 11 44 42](https://cloud.githubusercontent.com/assets/4543654/12351385/646c7148-bb7d-11e5-864f-e661bc8499bf.png)

Update: changed colors to rgba values so that the behaviour is also consistent on dark backgrounds.
Update 2: Improved targeting so that focus outline does not appear on hover or active state.
